/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "home": [],
    "newsletter.destroy": [],
    "contact.store": [],
    "newsletter.store": []
}
}
export {};
